// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuatlkehnvnnogrjdkzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1YXRsa2VobnZubm9ncmpka3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTk0NjcsImV4cCI6MjA2MDgzNTQ2N30.mk2wYlRlNkKqDA2hFrwHZbhsjQbjvvgXjSORRyYYTYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);